### ISSUE TITLE
Visualize detail of a single word's morphological variants (+diachronic variants).

### ISSUE THREAD

**Issue by Maartenvm** [TICCLAT/ticclat#39] opened 2019-06-25 09:09 UTC
Prefixes
Suffixes
Infixes

Typos
Change over time
Use over time

Filters, etc.
Single vs multiple corpora etc.

**Comment by jvdzwaan** [comment] 2019-07-24 14:54
Seems to be a duplicate of #30

**Comment by jvdzwaan** [comment] 2019-08-06 08:16
Moved to team eyra planning board.

**Closed by jvdzwaan** 2019-08-06 08:16 UTC
Labels: 20, High priority, Research, Visualization
